name: build-and-push
on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "release-*" ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Free up 10–20GB on the hosted runner
      - name: Free disk space
        run: |
          set -eux
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc \
                       /opt/hostedtoolcache/CodeQL /opt/hostedtoolcache/go \
                       /usr/local/.ghcup || true
          sudo docker image prune -af || true
          df -h

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        env:
          # plain progress creates smaller logs than tty
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          platforms: linux/amd64
          push: true
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/comfyui-new:latest
            ghcr.io/${{ github.repository_owner }}/comfyui-new:${{ github.sha }}
